# Generated by Django 6.0 on 2026-01-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_alter_order_table_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(choices=[('tea', 'Tea'), ('snacks', 'Snacks'), ('desserts', 'Desserts'), ('beverages', 'Beverages')], on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.category'),
        ),
    ]
