# Generated by Django 6.0 on 2026-01-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('tea', 'Tea'), ('snacks', 'Snacks'), ('desserts', 'Desserts'), ('beverages', 'Beverages')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
